#!/usr/bin/env python3
"""
PDF Report Generator
Converts markdown audit reports to professional PDFs
"""

from fpdf import FPDF
import re
from datetime import datetime
from typing import Dict, Any


class PDFReportGenerator(FPDF):
    """Custom PDF generator for audit reports"""

    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=15)

    def header(self):
        """Add header to each page"""
        self.set_font('Arial', 'B', 12)
        self.set_text_color(70, 70, 70)
        self.cell(0, 10, 'Publitz Game Audit Report', 0, 1, 'R')
        self.ln(5)

    def footer(self):
        """Add footer to each page"""
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

    def chapter_title(self, title: str, level: int = 1):
        """Add a chapter title"""
        self.ln(5)

        if level == 1:
            self.set_font('Arial', 'B', 16)
            self.set_text_color(41, 128, 185)  # Blue
        elif level == 2:
            self.set_font('Arial', 'B', 14)
            self.set_text_color(52, 73, 94)  # Dark gray
        else:
            self.set_font('Arial', 'B', 12)
            self.set_text_color(52, 73, 94)

        self.multi_cell(0, 8, title)
        self.ln(3)
        self.set_text_color(0, 0, 0)

    def chapter_body(self, body: str):
        """Add chapter body text"""
        self.set_font('Arial', '', 11)
        self.set_text_color(0, 0, 0)
        self.multi_cell(0, 6, body)
        self.ln(2)


def generate_pdf_report(
    report_markdown: str,
    game_name: str,
    report_type: str,
    audit_results: Dict[str, Any] = None
) -> bytes:
    """
    Generate a PDF report from markdown content

    Args:
        report_markdown: The markdown report content
        game_name: Name of the game
        report_type: Type of report (Pre-Launch or Post-Launch)
        audit_results: Optional audit results dictionary

    Returns:
        PDF file as bytes
    """
    pdf = PDFReportGenerator()
    pdf.add_page()

    # Title page
    pdf.set_font('Arial', 'B', 24)
    pdf.set_text_color(41, 128, 185)
    pdf.ln(30)
    pdf.cell(0, 15, f'{report_type} Audit Report', 0, 1, 'C')

    pdf.set_font('Arial', 'B', 18)
    pdf.set_text_color(52, 73, 94)
    pdf.cell(0, 10, game_name, 0, 1, 'C')

    pdf.set_font('Arial', '', 12)
    pdf.set_text_color(128, 128, 128)
    pdf.ln(10)
    pdf.cell(0, 8, f'Generated on {datetime.now().strftime("%B %d, %Y")}', 0, 1, 'C')

    # Add audit quality badge if available
    if audit_results:
        quality_score = audit_results.get('overall_quality_score', 0)
        needs_correction = audit_results.get('needs_correction', False)

        pdf.ln(15)
        pdf.set_font('Arial', 'B', 10)
        if not needs_correction and quality_score >= 80:
            pdf.set_text_color(39, 174, 96)  # Green
            badge_text = f'[YES] High Quality Report (Score: {quality_score}/100)'
        elif quality_score >= 60:
            pdf.set_text_color(243, 156, 18)  # Orange
            badge_text = f'[YES] Verified Report (Score: {quality_score}/100)'
        else:
            pdf.set_text_color(52, 152, 219)  # Blue
            badge_text = f'[YES] Analyzed Report (Score: {quality_score}/100)'

        pdf.cell(0, 8, badge_text, 0, 1, 'C')

    pdf.ln(10)
    pdf.set_font('Arial', 'I', 10)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(0, 6, 'This report was generated by Publitz AI-powered game auditing system, '
                         'combining data from Steam, SteamSpy, and advanced AI analysis.', 0, 'C')

    # Start new page for content
    pdf.add_page()

    # Parse and add markdown content
    _parse_markdown_to_pdf(pdf, report_markdown)

    # Return PDF as bytes
    return bytes(pdf.output())


def _clean_unicode_for_pdf(text: str) -> str:
    """Replace Unicode characters with ASCII equivalents for PDF compatibility"""
    # Replace checkmarks and symbols
    replacements = {
        '✓': '[YES]',
        '✗': '[NO]',
        '→': '->',
        '←': '<-',
        '↑': '^',
        '↓': 'v',
        '•': '*',
        '…': '...',
        '"': '"',
        '"': '"',
        ''': "'",
        ''': "'",
        '—': '-',
        '–': '-',
        '×': 'x',
        '÷': '/',
        '≈': '~',
        '≥': '>=',
        '≤': '<=',
        '≠': '!=',
        '°': ' degrees',
        '©': '(c)',
        '®': '(R)',
        '™': '(TM)',
        '€': 'EUR',
        '£': 'GBP',
        '¥': 'JPY',
    }

    for unicode_char, ascii_replacement in replacements.items():
        text = text.replace(unicode_char, ascii_replacement)

    # Remove any remaining non-ASCII characters
    text = text.encode('ascii', 'ignore').decode('ascii')

    return text


def _remove_markdown_formatting(text: str) -> str:
    """Remove all markdown formatting from text"""
    # Remove bold and italic markers (order matters!)
    text = re.sub(r'\*\*\*(.*?)\*\*\*', r'\1', text)  # Bold+Italic
    text = re.sub(r'\*\*(.*?)\*\*', r'\1', text)  # Bold
    text = re.sub(r'\*(.*?)\*', r'\1', text)  # Italic
    text = re.sub(r'___(.*?)___', r'\1', text)  # Bold+Italic (underscore)
    text = re.sub(r'__(.*?)__', r'\1', text)  # Bold (underscore)
    text = re.sub(r'_(.*?)_', r'\1', text)  # Italic (underscore)
    text = re.sub(r'`(.*?)`', r'\1', text)  # Inline code
    text = re.sub(r'~~(.*?)~~', r'\1', text)  # Strikethrough

    # Remove any stray asterisks or underscores that might be left
    # (in case of malformed markdown)
    text = re.sub(r'(?<!\w)\*+(?!\w)', '', text)  # Lone asterisks
    text = re.sub(r'(?<!\w)_+(?!\w)', '', text)  # Lone underscores

    return text


def _parse_markdown_to_pdf(pdf: PDFReportGenerator, markdown_text: str):
    """Parse markdown and add to PDF with proper formatting"""

    # Clean Unicode characters before parsing
    markdown_text = _clean_unicode_for_pdf(markdown_text)

    lines = markdown_text.split('\n')

    for line in lines:
        line = line.strip()

        if not line:
            pdf.ln(2)
            continue

        # H1 headers (# )
        if line.startswith('# '):
            title = line[2:].strip()
            title = _remove_markdown_formatting(title)
            pdf.chapter_title(title, level=1)

        # H2 headers (## )
        elif line.startswith('## '):
            title = line[3:].strip()
            title = _remove_markdown_formatting(title)
            pdf.chapter_title(title, level=2)

        # H3 headers (### )
        elif line.startswith('### '):
            title = line[4:].strip()
            title = _remove_markdown_formatting(title)
            pdf.chapter_title(title, level=3)

        # Bullet points (- or *)
        elif line.startswith('- ') or line.startswith('* '):
            text = line[2:].strip()
            text = _remove_markdown_formatting(text)
            pdf.set_font('Arial', '', 10)
            pdf.cell(10, 6, '*', 0, 0)
            pdf.multi_cell(0, 6, text)

        # Numbered lists
        elif re.match(r'^\d+\.', line):
            text = re.sub(r'^\d+\.\s*', '', line)
            text = _remove_markdown_formatting(text)
            pdf.set_font('Arial', '', 10)
            pdf.multi_cell(0, 6, f'  {text}')

        # Regular paragraph
        else:
            text = _remove_markdown_formatting(line)

            # Skip horizontal rules
            if text.strip() in ['---', '___', '***', '']:
                pdf.ln(5)
                continue

            if text:
                pdf.chapter_body(text)


def create_downloadable_pdf(
    report_markdown: str,
    game_name: str,
    report_type: str,
    audit_results: Dict[str, Any] = None
) -> tuple[bytes, str]:
    """
    Create a downloadable PDF report

    Returns:
        Tuple of (pdf_bytes, filename)
    """
    pdf_bytes = generate_pdf_report(report_markdown, game_name, report_type, audit_results)

    # Generate filename
    safe_game_name = re.sub(r'[^\w\s-]', '', game_name).strip().replace(' ', '_')
    timestamp = datetime.now().strftime('%Y%m%d')
    filename = f"{safe_game_name}_{report_type}_Audit_{timestamp}.pdf"

    return pdf_bytes, filename
